/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v7.0
processor: S32K148
package_id: S32K148_LQFP144
mcu_data: s32sdk_s32k1xx_rtm_400
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 23631c9c-96af-4ef1-a29b-83139b23b73e
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_phy_1.h"

/*******************************************************************************
 * phy_1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'phy_1'
- type: 'phy'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'phy'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - phy:
    - phy_configs:
      - 0:
        - phyStdCfg:
          - name: 'PHY_INSTANCE_0'
          - type: 'PHY_TYPE_TJA110X'
          - location: 'PHY_LOCATION_EXTERNAL'
          - enetInstance: '0'
          - addr: '0'
          - role: 'PHY_ROLE_MASTER'
          - linkUpEventCB: 'link_up'
          - linkDownEventCB: 'link_down'
          - autonegCompleteCB: 'NULL'
          - autonegFailedCB: 'NULL'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
#define PHY_TYPE_TJA110X  (0U)

/*! @brief Array of pointers towards the driver structures */
phy_driver_t *phyDrivers[N_PHY_DRIVERS] = {&PHY_driver_tja110x};

/*! @brief Array of PHY configuration structures */
phy_config_t  phyConfig[N_PHY_DEVS] = {
	{
	  .type = PHY_TYPE_TJA110X,
	  .location = PHY_LOCATION_EXTERNAL,
	  .enetInstance = 0U,
	  .addr = 0UL,
	  .role = PHY_ROLE_MASTER,
	  .linkUpEventCB = link_up,
	  .linkDownEventCB = link_down,
	  .autonegCompleteCB = NULL,
	  .autonegFailedCB = NULL
	},
};


